jenkins:
  image: jenkins
  restart: always
  ports:
    - "9000:8080"
    - "465:465"
  environment:
    - JAVA_OPTS=-Duser.timezone=America/Sao_Paulo
  volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
    - /usr/bin/docker:/usr/bin/docker
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    - /tmp/log-sis:/tmp/log-sis
  user: root
  container_name: jenkins
