skills_neo4j:
  container_name: skills_neo4j
  image: neo4j:latest
  links:
    - es_neo4j 
  ports:
    - "7474:7474"
  volumes:
    - "$PWD/neo4j/data:/data"
    - "$PWD/neo4j/conf:/conf"
    - "$PWD/neo4j/plugins:/plugins"

es_neo4j:
  container_name: es_neo4j
  command: elasticsearch
  image: elasticsearch:2
  volumes:
    - "$PWD/es_neo4j/data:/usr/share/elasticsearch/data"
  ports:
    - "9200:9200"
    - "9300:9300"
